steps:
  # 1. Build the container image using the Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/ski-game:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/ski-game:latest',
      '.'
    ]

  # 2. Push the container image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ski-game']

# Auto-register pushed images in the project container registry
images:
  - 'gcr.io/$PROJECT_ID/ski-game:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/ski-game:latest'
